// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvp5w7dwEvGQXWkm2KA0vMveyOEVmKA-0',
    appId: '1:69660124589:web:2d4f9d9260f94a46322d24',
    messagingSenderId: '69660124589',
    projectId: 'fit-takip-dev',
    authDomain: 'fit-takip-dev.firebaseapp.com',
    storageBucket: 'fit-takip-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvp5w7dwEvGQXWkm2KA0vMveyOEVmKA-0',
    appId: '1:69660124589:android:2d4f9d9260f94a46322d24',
    messagingSenderId: '69660124589',
    projectId: 'fit-takip-dev',
    storageBucket: 'fit-takip-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvp5w7dwEvGQXWkm2KA0vMveyOEVmKA-0',
    appId: '1:69660124589:ios:2d4f9d9260f94a46322d24',
    messagingSenderId: '69660124589',
    projectId: 'fit-takip-dev',
    storageBucket: 'fit-takip-dev.firebasestorage.app',
    iosBundleId: 'com.example.mobil_proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvp5w7dwEvGQXWkm2KA0vMveyOEVmKA-0',
    appId: '1:69660124589:ios:2d4f9d9260f94a46322d24',
    messagingSenderId: '69660124589',
    projectId: 'fit-takip-dev',
    storageBucket: 'fit-takip-dev.firebasestorage.app',
    iosBundleId: 'com.example.mobil_proje',
  );
}
